{
  inputs = {
    # Nix Packages collection & NixOS
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    # ❄️ Simplify Nix Flakes with the module system
    flake-parts.url = "github:hercules-ci/flake-parts";

    # Import all nix files in a directory tree.
    import-tree.url = "github:vic/import-tree";

    # Manage a user environment using Nix
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Modular, extensible and distro-agnostic Neovim configuration framework for Nix/NixOS
    nvf.url = "github:notashelf/nvf";

    # Community-driven Nix Flake for the Zen browser
    zen-browser.url = "github:0xc000022070/zen-browser-flake";

    # Data provider service and backend for building custom application launchers
    elephant.url = "github:abenz1267/elephant";

    # Wayland-native application runner
    walker = {
      url = "github:abenz1267/walker";
      inputs.elephant.follows = "elephant";
    };
  };

  outputs = inputs:
    inputs.flake-parts.lib.mkFlake {inherit inputs;} {
      imports = [
        # enable the flake.modules feature
        inputs.flake-parts.flakeModules.modules

        # auto-import all files inside your modules directory
        (inputs.import-tree ./modules)
      ];

      systems = [
        "x86_64-linux"
      ];

      flake = {
        nixosConfigurations.c04o = inputs.nixpkgs.lib.nixosSystem {
          modules = [
            # cache acceleration layer
            {
              nix.settings = {
                extra-substituters = [
                  "https://walker.cachix.org"
                  "https://walker-git.cachix.org"
                ];
                extra-trusted-public-keys = [
                  "walker.cachix.org-1:fG8q+uAaMqhsMxWjwvk0IMb4mFPFLqHjuvfwQxE4oJM="
                  "walker-git.cachix.org-1:vmC0ocfPWh0S/vRAQGtChuiZBTAe4wiKDeyyXM0/7pM="
                ];
              };
            }
            ./hardware-configuration.nix

            # pull in the combined nixos configuration generated by modules
            inputs.self.flakeModules.nixos.c04o

            inputs.home-manager.nixosModules.home-manager
            {
              home-manager.useGlobalPkgs = true;
              home-manager.useUserPackages = true;
              # pull in the combined home manager configuration for user
              home-manager.users.coni = inputs.self.flakeModules.homeManager.coni;
            }
          ];
        };
      };
    };
}
