{
  inputs = {
    # Nix Packages collection & NixOS
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    # ❄️ Simplify Nix Flakes with the module system
    flake-parts.url = "github:hercules-ci/flake-parts";

    # Import all nix files in a directory tree.
    import-tree.url = "github:vic/import-tree";

    # Manage a user environment using Nix
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Modular, extensible and distro-agnostic Neovim configuration framework for Nix/NixOS
    nvf.url = "github:notashelf/nvf";

    # Community-driven Nix Flake for the Zen browser
    zen-browser.url = "github:0xc000022070/zen-browser-flake";
  };

  outputs = inputs:
    inputs.flake-parts.lib.mkFlake {inherit inputs;} {
      imports = [
        # enable the flake.modules feature
        inputs.flake-parts.flakeModules.modules

        # auto-import all files inside your modules directory
        (inputs.import-tree ./modules)
      ];

      systems = [
        "x86_64-linux"
      ];

      flake = {
        nixosConfigurations.c04o = inputs.nixpkgs.lib.nixosSystem {
          modules = [
            ./hardware-configuration.nix

            # pull in the combined nixos configuration generated by modules
            inputs.self.flakeModules.nixos.c04o

            inputs.home-manager.nixosModules.home-manager
            {
              home-manager.useGlobalPkgs = true;
              home-manager.useUserPackages = true;
              # pull in the combined home manager configuration for user
              home-manager.users.coni = inputs.self.flakeModules.homeManager.coni;
            }
          ];
        };
      };
    };
}
