name: ci

# when to run the ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # clone repo in runner
      - uses: actions/checkout@v5

      # installer
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # check that nix files are formatted
      - name: check formatting
        run: nix run nixpkgs#alejandra -- --check .

      # ensure all inputs/outputs are right
      - name: check flake
        run: nix flake check

  build:
    name: build
    runs-on: ubuntu-latest
    # wait for lint job to pass
    needs: lint
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # naturally runs if the lint job passed
      - name: Build NixOS
        run: nix build .#nixosConfigurations.c04o.config.system.build.toplevel
